=== hyptpc/k18-analyzer/e73_2024/param/schema/channel_map.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    attributeFormDefault="unqualified"
    elementFormDefault="unqualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="channel_map" type="channel_mapType"/>


  <!-- _____________________________________________________________________-->
  <!-- _____________________________________________________________________-->
  <!-- ________________________________________________________________________
       attributeGroup definition
  -->
  <!-- ________________________________________________________________________
       <unpackerAttrs>
  -->
  <xs:attributeGroup name="unpackerAttrs">
    <xs:attribute name="decode" type="xs:string" default="y"/>
    <xs:attribute name="dump"   type="xs:string" default="n"/>
    <xs:attribute name="unpack" type="xs:string" default="y"/>
  </xs:attributeGroup>

  <!-- ________________________________________________________________________
       <finesseAttrs>
  -->
  <xs:attributeGroup name="finesseAttrs">
    <xs:attribute name="slot" type="xs:string" use="required"/>
    <xs:attributeGroup ref="unpackerAttrs"/>
  </xs:attributeGroup>

  <!-- ________________________________________________________________________
       <tkoAttrs>
  -->
  <xs:attributeGroup name="tkoAttrs">
    <xs:attribute name="ma" type="xs:string" use="required"/>
    <xs:attributeGroup ref="unpackerAttrs"/>
  </xs:attributeGroup>

  <!-- ________________________________________________________________________
       <feraAttrs>
  -->
  <xs:attributeGroup name="feraAttrs">
    <xs:attribute name="ma" type="xs:string" use="required"/>
    <xs:attributeGroup ref="unpackerAttrs"/>
  </xs:attributeGroup>

  <!-- ________________________________________________________________________
       <vmeAttrs>
  -->
  <xs:attributeGroup name="vmeAttrs">
    <xs:attribute name="address" type="xs:string" use="required"/>
    <xs:attributeGroup ref="unpackerAttrs"/>
  </xs:attributeGroup>

  <!-- ________________________________________________________________________
       <asadAttrs>
  -->
  <xs:attributeGroup name="asadAttrs">
    <xs:attribute name="address" type="xs:string" use="required"/>
    <xs:attributeGroup ref="unpackerAttrs"/>
  </xs:attributeGroup>

  <!-- ________________________________________________________________________
       <nodeAttrs>
  -->
  <xs:attributeGroup name="nodeAttrs">
    <xs:attribute name="node_id" type="xs:string" use="required"/>
    <xs:attribute name="name"    type="xs:string" use="required"/>
    <xs:attributeGroup ref="unpackerAttrs"/>
  </xs:attributeGroup>



  <!-- _____________________________________________________________________-->
  <!-- _____________________________________________________________________-->
  <!-- ________________________________________________________________________
       group definition
  -->
  <!-- ________________________________________________________________________
       <feGroup>
  -->
  <xs:group name="feGroup">
    <xs:choice>
      <xs:element name="FE"  type="FEType"/>
      <xs:element name="for" type="fe_forType"/>
    </xs:choice>
  </xs:group>

  <!-- ________________________________________________________________________
       <finesseGroup>
  -->
  <xs:group name="finesseGroup">
    <xs:choice>
      <xs:element name="FinesseEncoderPPG" type="FinesseType"/>
      <xs:element name="FinesseEncoder"    type="FinesseType"/>
      <xs:element name="FinessePtdc"       type="FinesseType"/>
      <xs:group   ref="feGroup"/>
    </xs:choice>
  </xs:group>

  <!-- ________________________________________________________________________
       <tkoGroup>
  -->
  <xs:group name="tkoGroup">
    <xs:choice>
      <xs:element name="Tko"      type="TkoType"/>
      <xs:element name="TkoDrT"   type="TkoType"/>
      <xs:element name="TkoDrTII" type="TkoType"/>
      <xs:element name="TkoRm"    type="TkoRmType"/>
      <xs:element name="TkoMHTdc" type="TkoMHTdcType"/>
      <xs:element name="TkoMHTdcCSds" type="TkoMHTdcCSdsType"/>
      <xs:group   ref="feGroup"/>
    </xs:choice>
  </xs:group>

  <!-- ________________________________________________________________________
       <feraGroup>
  -->
  <xs:group name="feraGroup">
    <xs:choice>
      <xs:element name="FeraAD413A"   type="FeraType"/>
      <xs:element name="Fera3377"     type="FeraType"/>
      <xs:group   ref="feGroup"/>
    </xs:choice>
  </xs:group>

  <!-- ________________________________________________________________________
       <vmeModuleGroup>
  -->
  <xs:group name="vmeModuleGroup">
    <xs:choice>
      <xs:element name="VmeAPVDaq"     type="VmeModuleType"/>
      <xs:element name="VmeSmp"        type="VmeSmpType"/>
      <xs:element name="VmeRpv130"     type="VmeModuleType"/>
      <xs:element name="VmeRpv100"     type="VmeModuleType"/>
      <xs:element name="VmeCaenV775"   type="VmeModuleType"/>
      <xs:element name="VmeCaenV792"   type="VmeModuleType"/>
      <xs:element name="VmeCaenV820"   type="VmeModuleType"/>
      <xs:element name="VmeCaenV830"   type="VmeModuleType"/>
      <xs:element name="VmeCaenV1724"  type="VmeModuleType"/>
      <xs:element name="VmeEmc"        type="VmeModuleType"/>
      <xs:element name="VmeInputReg"   type="VmeModuleType"/>
      <xs:element name="VmeTdc64M"     type="VmeModuleType"/>
      <xs:element name="VmeRm"         type="VmeModuleType"/>
      <xs:element name="VmeAmt"        type="VmeModuleType"/>
      <xs:element name="VmeUmem"       type="VmeUmemType"/>
      <xs:element name="HBJTimeStamp"  type="VmeModuleType"/>
      <xs:element name="VVmeCamacRm"   type="VmeModuleType"/>
      <xs:element name="VVmeFERA4300B" type="VmeModuleType"/>
      <xs:element name="VVmeCoinReg"   type="VmeModuleType"/>
      <xs:element name="VmeV1290A"     type="VmeModuleType"/>
      <xs:group   ref="feGroup"/>
    </xs:choice>
  </xs:group>

  <!-- ________________________________________________________________________
       <asadGroup>
  -->
  <xs:group name="asadModuleGroup">
    <xs:choice>
      <xs:element name="GetAsAd"     type="AsAdModuleType"/>
      <xs:group   ref="feGroup"/>
    </xs:choice>
  </xs:group>

  <!-- ________________________________________________________________________
       <nodeGroup>
  -->
  <xs:group name="nodeGroup">
    <xs:choice>
      <xs:element name="SoyTimeStamp"    type="DAQNodeType"/>
      <xs:element name="Hul3DMtx"        type="DAQNodeType"/>
      <xs:element name="HulScaler"       type="DAQNodeType"/>
      <xs:element name="HulMHTdc"        type="DAQNodeType"/>
      <xs:element name="HulHRTdc"        type="DAQNodeType"/>
      <xs:element name="HulMsT"          type="DAQNodeType"/>
      <xs:element name="HulMassTrigFera" type="DAQNodeType"/>
      <xs:element name="HulUmem"         type="DAQNodeType"/>
      <xs:element name="HulResetTime"    type="DAQNodeType"/>
      <xs:element name="VmeMaster"       type="VmeMasterType"/>
      <xs:element name="GetCoBoMaster"   type="GetCoBoMasterType"/>
      <xs:element name="Copper"          type="CopperType"/>
      <xs:element name="CopperLite"      type="CopperType"/>
      <xs:element name="Easiroc"         type="DAQNodeType"/>
      <xs:element name="VmeEasiroc"      type="DAQNodeType"/>
      <xs:element name="DAQNode"         type="DAQNodeType"/>
      <xs:group   ref="feGroup"/>
    </xs:choice>
  </xs:group>

  <!-- ________________________________________________________________________
       <unpackerGroup>
  -->
  <xs:group name="unpackerLoopGroup">
    <xs:choice>
      <xs:element name="DAQNode"            type="DAQNodeType"/>
      <xs:element name="Copper"             type="CopperType"/>
      <xs:element name="CopperLite"         type="CopperType"/>
      <xs:element name="Easiroc"            type="DAQNodeType"/>
      <xs:element name="VmeEasiroc"         type="DAQNodeType"/>
      <xs:element name="VmeMaster"          type="VmeMasterType"/>
      <xs:element name="GetCoBoMaster"      type="GetCoBoMasterType"/>
      <xs:element name="SoyTimeStamp"       type="DAQNodeType"/>
      <xs:element name="Hul3DMtx"           type="DAQNodeType"/>
      <xs:element name="HulScaler"          type="DAQNodeType"/>
      <xs:element name="HulMHTdc"           type="DAQNodeType"/>
      <xs:element name="HulHRTdc"           type="DAQNodeType"/>
      <xs:element name="HulMsT"             type="DAQNodeType"/>
      <xs:element name="HulMassTrigFera"    type="DAQNodeType"/>

      <xs:element name="VmeRpv100"          type="VmeModuleType"/>
      <xs:element name="VmeRpv130"          type="VmeModuleType"/>
      <xs:element name="VmeCaenV775"        type="VmeModuleType"/>
      <xs:element name="VmeCaenV792"        type="VmeModuleType"/>
      <xs:element name="VmeCaenV820"        type="VmeModuleType"/>
      <xs:element name="VmeCaenV830"        type="VmeModuleType"/>
      <xs:element name="VmeCaenV1724"       type="VmeModuleType"/>
      <xs:element name="VmeEmc"             type="VmeModuleType"/>
      <xs:element name="VmeInputReg"        type="VmeModuleType"/>
      <xs:element name="VmeTdc64M"          type="VmeModuleType"/>
      <xs:element name="VmeSmp"             type="VmeSmpType"/>
      <xs:element name="VmeRm"              type="VmeModuleType"/>
      <xs:element name="VmeAmt"             type="VmeModuleType"/>
      <xs:element name="VmeUmem"            type="VmeModuleType"/>
      <xs:element name="HBJTimeStamp"       type="VmeModuleType"/>
      <xs:element name="VVmeCamacRm"        type="VmeModuleType"/>
      <xs:element name="VVmeFERA4300B"      type="VmeModuleType"/>
      <xs:element name="VVmeCoinReg"        type="VmeModuleType"/>
      <xs:element name="APVDaq"             type="VmeModuleType"/>
      <xs:element name="VmeV1290A"          type="VmeModuleType"/>

      <xs:element name="Tko"                type="TkoType"/>
      <xs:element name="TkoDrT"             type="TkoType"/>
      <xs:element name="TkoDrTII"           type="TkoType"/>
      <xs:element name="TkoMHTdc"           type="TkoMHTdcType"/>
      <xs:element name="TkoMHTdcCSds"       type="TkoMHTdcCSdsType"/>
      <xs:element name="TkoRm"              type="TkoRmType"/>

      <xs:element name="FeraAD413A"         type="FeraType"/>
      <xs:element name="Fera3377"           type="FeraType"/>

      <xs:element name="FinessePtdc"        type="FinesseType"/>
      <xs:element name="FinesseEncoder"     type="FinesseType"/>
      <xs:element name="FinesseEncoderPPG"  type="FinesseType"/>
      <xs:element name="FinesseEncoderPtdc" type="FinesseType"/>

      <xs:element name="GetAsAd"            type="AsAdModuleType"/>

      <xs:element name="FE"  type="FEType"/>
      <xs:element name="for" type="fe_forType"/>
    </xs:choice>
  </xs:group>

  <!-- _____________________________________________________________________-->
  <!-- _____________________________________________________________________-->
  <!-- ________________________________________________________________________
       complexType definition
  -->
  <!-- ________________________________________________________________________
       <channel_mapType>
  -->
  <xs:complexType name="channel_mapType">
    <xs:group ref="nodeGroup"/>
  </xs:complexType>

  <!-- ________________________________________________________________________
       <DType>
  -->
  <xs:complexType name="DType">
    <xs:attribute name="Device"	 type="xs:string" use="optional"/>
    <xs:attribute name="device"	 type="xs:string" default="0"/>
    <xs:attribute name="Plane"   type="xs:string" use="optional"/>
    <xs:attribute name="plane"   type="xs:string" default="0"/>
    <xs:attribute name="Segment" type="xs:string" use="optional"/>
    <xs:attribute name="segment" type="xs:string" default="0"/>
    <xs:attribute name="Ch"      type="xs:string" use="optional"/>
    <xs:attribute name="ch"      type="xs:string" default="0"/>
    <xs:attribute name="Data"    type="xs:string" use="optional"/>
    <xs:attribute name="data"    type="xs:string" default="0"/>
  </xs:complexType>

  <!-- ________________________________________________________________________
       <FEType>
  -->
  <xs:complexType name="FEType">
    <xs:all>
      <xs:element name="D" type="DType"/>
    </xs:all>
    <xs:attribute name="ch"   type="xs:string" default="0"/>
    <xs:attribute name="data" type="xs:string" default="0"/>
  </xs:complexType>

  <!-- ________________________________________________________________________
       <FinesseType>
  -->
  <xs:complexType name="FinesseType">
    <xs:group     ref="feGroup" minOccurs="0" maxOccurs="unbounded"/>
    <xs:attributeGroup ref="finesseAttrs"/>
  </xs:complexType>

  <!-- ________________________________________________________________________
       <TkoType>
  -->
  <xs:complexType name="TkoType">
    <xs:group ref="feGroup" minOccurs="0" maxOccurs="32"/>
    <xs:attributeGroup ref="tkoAttrs"/>
  </xs:complexType>

  <!-- ________________________________________________________________________
       <TkoRmType>
  -->
  <xs:complexType name="TkoRmType">
    <xs:group ref="feGroup" minOccurs="0" maxOccurs="4"/>
    <xs:attributeGroup ref="tkoAttrs"/>
  </xs:complexType>
  <!-- ________________________________________________________________________
       <TkoMHTdcType>
  -->
  <xs:complexType name="TkoMHTdcType">
    <xs:group ref="feGroup" minOccurs="0" maxOccurs="130"/>
    <xs:attributeGroup ref="tkoAttrs"/>
  </xs:complexType>

  <!-- ________________________________________________________________________
       <TkoMHTdcCSdsType>
  -->
  <xs:complexType name="TkoMHTdcCSdsType">
    <xs:group ref="feGroup" minOccurs="0" maxOccurs="130"/>
    <xs:attributeGroup ref="tkoAttrs"/>
  </xs:complexType>

  <!-- ________________________________________________________________________
       <FeraType>
  -->
  <xs:complexType name="FeraType">
    <xs:group ref="feGroup" minOccurs="0" maxOccurs="32"/>
    <xs:attributeGroup ref="feraAttrs"/>
  </xs:complexType>


  <!-- ________________________________________________________________________
       <VmeSmpType>
  -->
  <xs:complexType name="VmeSmpType">
    <xs:group ref="tkoGroup" minOccurs="0" maxOccurs="unbounded"/>
    <xs:attributeGroup ref="vmeAttrs"/>
  </xs:complexType>

  <!-- ________________________________________________________________________
       <VmeUmemType>
  -->
  <xs:complexType name="VmeUmemType">
    <xs:group ref="feraGroup" minOccurs="0" maxOccurs="unbounded"/>
    <xs:attributeGroup ref="vmeAttrs"/>
  </xs:complexType>

  <!-- ________________________________________________________________________
       <VmeModuleType>
  -->
  <xs:complexType name="VmeModuleType">
    <xs:group ref="feGroup" minOccurs="0" maxOccurs="unbounded"/>
    <xs:attributeGroup ref="vmeAttrs"/>
  </xs:complexType>

  <!-- ________________________________________________________________________
       <VmeMasterType>
  -->
  <xs:complexType name="VmeMasterType">
    <xs:group ref="vmeModuleGroup" minOccurs="0" maxOccurs="unbounded"/>
    <xs:attributeGroup ref="nodeAttrs"/>
  </xs:complexType>
  <!-- ________________________________________________________________________
       <AsAdModuleType>
  -->
  <xs:complexType name="AsAdModuleType">
    <xs:group ref="feGroup" minOccurs="0" maxOccurs="unbounded"/>
    <xs:attributeGroup ref="asadAttrs"/>
  </xs:complexType>
  <!-- ________________________________________________________________________
       <GetCoBoMasterType>
  -->
  <xs:complexType name="GetCoBoMasterType">
    <xs:group ref="asadModuleGroup" minOccurs="0" maxOccurs="unbounded"/>
    <xs:attributeGroup ref="nodeAttrs"/>
  </xs:complexType>
  <!-- ________________________________________________________________________
       <CopperType>
  -->
  <xs:complexType name="CopperType">
    <xs:group ref="finesseGroup" minOccurs="0" maxOccurs="4"/>
    <xs:attributeGroup ref="nodeAttrs"/>
  </xs:complexType>

  <!-- ________________________________________________________________________
       <DAQNodeType>
  -->
  <xs:complexType name="DAQNodeType">
    <xs:group ref="nodeGroup" minOccurs="0" maxOccurs="unbounded"/>
    <xs:attributeGroup ref="nodeAttrs"/>
  </xs:complexType>

  <!-- ________________________________________________________________________
       <fe_forType>
  -->
  <xs:complexType name="fe_forType">
    <xs:group     ref="unpackerLoopGroup" minOccurs="0" maxOccurs="unbounded"/>
    <xs:attribute name="var"  type="xs:string" use="required"/>
    <xs:attribute name="from" type="xs:string" use="required"/>
    <xs:attribute name="to"   type="xs:string" use="required"/>
    <xs:attribute name="step" type="xs:int"    default="1"/>
  </xs:complexType>

</xs:schema>

=== hyptpc/k18-analyzer/e73_2024/param/CMAP/channel_map_raw.xml
<?xml version="1.0" encoding="UTF-8" ?>

<channel_map xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="schema/channel_map.xsd">
  <DAQNode node_id="1" name="k18eb">
    <!--________________________________________________________________-->
    <VmeMaster node_id="513" name="vme01">
      <VmeRm address="0xff010000">
    	<for var="ch" from="0" to="1"><for var="data" from="0" to="3">
    	  <FE ch="ch" data="data"><D Device="VME-RM" Plane="vme01" ch="ch" data="data"/></FE>
    	</for></for>
      </VmeRm>
      <VmeCaenV792 address="0xad010000">
	<for var="ch" from="0" to="31">
    	  <FE ch="ch"><D Device="Counter" segment="ch" ch="0" data="0"/></FE>
    	</for>
      </VmeCaenV792>
      <VmeCaenV792 address="0xad020000">
	<for var="ch" from="0" to="31">
    	  <FE ch="ch"><D Device="QDC2" segment="ch" ch="0" data="0"/></FE>
    	</for>
      </VmeCaenV792>
      <VmeCaenV792 address="0xad030000">
	<for var="ch" from="0" to="31">
    	  <FE ch="ch"><D Device="QDC3" segment="ch" ch="0" data="0"/></FE>
    	</for>
      </VmeCaenV792>
      <VmeEmc address="0xe3c00000">
	<for var="data" from="0" to="5">
	  <FE data="data"><D Device="EMC" data="data"/></FE>
	</for>
      </VmeEmc>
    </VmeMaster>
    <!-- ________________________________________________________________ -->
    <HulHRTdc node_id="1657" name="hulhrtdc-121">
      <for var="ch" from="0" to="63"><for var="data" from="0" to="3">
	<FE ch="ch" data="data"><D Device="HRTDC1" segment="ch" ch="0" data="data"/></FE>
      </for></for>
    </HulHRTdc>
    <!-- ________________________________________________________________ -->
    <HulHRTdc node_id="1658" name="hulhrtdc-122">
      <for var="ch" from="0" to="63"><for var="data" from="0" to="3">
	<FE ch="ch" data="data"><D Device="HRTDC2" segment="ch" ch="0" data="data"/></FE>
      </for></for>
    </HulHRTdc>
    <!-- ________________________________________________________________ -->
    <HulHRTdc node_id="1659" name="hulhrtdc-123">
      <for var="ch" from="0" to="63"><for var="data" from="0" to="3">
	<FE ch="ch" data="data"><D Device="HRTDC3" segment="ch" ch="0" data="data"/></FE>
      </for></for>
    </HulHRTdc>
    <!-- ________________________________________________________________ -->
    <HulMHTdc node_id="1674" name="hulmhtdc-138">
      <for var="ch" from="0" to="127"><for var="data" from="0" to="2">
    	<FE ch="ch" data="data"><D Device="TriggerFlag" segment="ch" ch="0" data="data"/></FE>
      </for></for>
    </HulMHTdc>
    <!-- ________________________________________________________________ -->
    <HulScaler node_id="1675" name="hulscaler-139">
      <for var="ch" from="0" to="63"><for var="data" from="0" to="4">
    	<FE ch="ch" data="data"><D Device="Scaler" plane="0" ch="ch" data="data"/></FE>
      </for></for>
    </HulScaler>
    <!-- ______________________________
    <HulScaler node_id="1676" name="hulscaler-140">
      <for var="ch" from="0" to="63"><for var="data" from="0" to="4">
    	<FE ch="ch" data="data"><D Device="Scaler" plane="0" ch="ch" data="data"/></FE>
      </for></for>
    </HulScaler>
    __________________________________ -->
    <!-- ________________________________________________________________ -->
    <HulHRTdc node_id="1678" name="hulhrtdc-142">
      <for var="ch" from="0" to="63"><for var="data" from="0" to="3">
	<FE ch="ch" data="data"><D Device="HRTDC4" segment="ch" ch="0" data="data"/></FE>
      </for></for>
    </HulHRTdc>
    <!-- ________________________________________________________________ -->
    <HulHRTdc node_id="1679" name="hulhrtdc-143">
      <for var="ch" from="0" to="63"><for var="data" from="0" to="3">
	<FE ch="ch" data="data"><D Device="HRTDC5" segment="ch" ch="0" data="data"/></FE>
      </for></for>
    </HulHRTdc>
    <!-- ________________________________________________________________ -->
    <HulHRTdc node_id="1680" name="hulhrtdc-144">
      <for var="ch" from="0" to="63"><for var="data" from="0" to="3">
	<FE ch="ch" data="data"><D Device="HRTDC6" segment="ch" ch="0" data="data"/></FE>
      </for></for>
    </HulHRTdc>

    <!--BPC/HRTDC RM______________________________________________________________ -->
    <HulMHTdc node_id="1637" name="hulmhtdc-101">
      <for var="data" from="0" to="6">
	<FE ch="0" data="data"><D Device="HUL-RM" segment="1" ch="0" data="data "/></FE>
      </for>
      <for var="ch" from="1" to="127"><for var="data" from="0" to="3">
    	  <FE ch="ch" data="data"><D Device="VMEdummy" plane="101" segment="ch" ch="0" data="data+1"/></FE>
      </for></for>
    </HulMHTdc>
    <!--BPC______________________________________________________________ -->
    <HulMHTdc node_id="1638" name="hulmhtdc-102">
      <for var="ch" from="0" to="15"><for var="data" from="0" to="2">
    	<FE ch="ch" data="data"><D Device="BPC2" plane="0" ch="ch" data="data"/></FE>
    	<FE ch="ch + 16" data="data"><D Device="BPC2" plane="0" ch="31 - ch" data="data"/></FE>
      </for></for>
      <for var="ch" from="32" to="47"><for var="data" from="0" to="2">
    	<FE ch="ch" data="data"><D Device="BPC2" plane="1" ch="47 - ch" data="data"/></FE>
    	<FE ch="ch + 16" data="data"><D Device="BPC2" plane="1" ch="ch - 16" data="data"/></FE>
      </for></for>
      <for var="ch" from="64" to="79"><for var="data" from="0" to="2">
    	<FE ch="ch" data="data"><D Device="BPC2" plane="2" ch="ch - 64" data="data"/></FE>
    	<FE ch="ch + 16" data="data"><D Device="BPC2" plane="2" ch="95 - ch" data="data"/></FE>
      </for></for>
      <for var="ch" from="96" to="111"><for var="data" from="0" to="2">
    	<FE ch="ch" data="data"><D Device="BPC2" plane="3" ch="111 - ch" data="data"/></FE>
    	<FE ch="ch + 16" data="data"><D Device="BPC2" plane="3" ch="ch - 80" data="data"/></FE>
      </for></for>
    </HulMHTdc>
    <!--BPC2______________________________________________________________ -->
    <HulMHTdc node_id="1639" name="hulmhtdc-103">
      <for var="ch" from="0" to="15"><for var="data" from="0" to="2">
    	<FE ch="ch" data="data"><D Device="BPC2" plane="4" ch="ch" data="data"/></FE>
    	<FE ch="ch + 16" data="data"><D Device="BPC2" plane="4" ch="31 - ch" data="data"/></FE>
      </for></for>
      <for var="ch" from="32" to="47"><for var="data" from="0" to="2">
    	<FE ch="ch" data="data"><D Device="BPC2" plane="5" ch="47 - ch" data="data"/></FE>
    	<FE ch="ch + 16" data="data"><D Device="BPC2" plane="5" ch="ch - 16" data="data"/></FE>
      </for></for>
      <for var="ch" from="64" to="79"><for var="data" from="0" to="2">
    	<FE ch="ch" data="data"><D Device="BPC2" plane="6" ch="ch - 64" data="data"/></FE>
    	<FE ch="ch + 16" data="data"><D Device="BPC2" plane="6" ch="95 - ch" data="data"/></FE>
      </for></for>
      <for var="ch" from="96" to="111"><for var="data" from="0" to="2">
    	<FE ch="ch" data="data"><D Device="BPC2" plane="7" ch="111 - ch" data="data"/></FE>
    	<FE ch="ch + 16" data="data"><D Device="BPC2" plane="7" ch="ch - 80" data="data"/></FE>
      </for></for>
    </HulMHTdc>
    <!-- ________________________________________________________________ -->
  </DAQNode>    
</channel_map>
