=== hyptpc/k18-analyzer/e73_2024/param/schema/digit.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
    attributeFormDefault="unqualified"
    elementFormDefault="unqualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="digit_data" type="digit_dataType"/>




  <!-- ______________________________________________________________________-->
  <!-- ______________________________________________________________________-->
  <!-- _________________________________________________________________________
       attributeGroup definition
  -->

  <!-- _________________________________________________________________________
       <digitAttrs>
  -->
  <xs:attributeGroup name="digitAttrs">
    <xs:attribute name="id"   type="xs:string" default="0"/>
    <xs:attribute name="name" type="xs:string" use="optional"/>
  </xs:attributeGroup>



  <!-- ______________________________________________________________________-->
  <!-- ______________________________________________________________________-->
  <!-- _________________________________________________________________________
       group definition
  -->

  <!-- _________________________________________________________________________
       <dataGroup>
  -->
  <xs:group name="dataGroup">
    <xs:choice>
      <xs:element name="data" type="dataType"/>
      <xs:element name="for"  type="forType"/>
    </xs:choice>
  </xs:group>

  <!-- _________________________________________________________________________
       <chGroup>
  -->
  <xs:group name="chGroup">
    <xs:choice>
      <xs:element name="ch" type="chType"/>
      <xs:group	  ref="dataGroup"/>
    </xs:choice>
  </xs:group>

  <!-- _________________________________________________________________________
       <segmentGroup>
  -->
  <xs:group name="segmentGroup">
    <xs:choice>
      <xs:element name="segment" type="segmentType"/>
      <xs:group	  ref="chGroup"/>
    </xs:choice>
  </xs:group>

  <!-- _________________________________________________________________________
       <planeGroup>
  -->
  <xs:group name="planeGroup">
    <xs:choice>
      <xs:element name="plane"  type="planeType"/>
      <xs:group	  ref="segmentGroup"/>
    </xs:choice>
  </xs:group>

  <!-- _________________________________________________________________________
       <deviceGroup>
  -->
  <xs:group name="deviceGroup">
    <xs:choice>
      <xs:element  name="device"  type="deviceType"/>
      <xs:group    ref="planeGroup"/>
    </xs:choice>
  </xs:group>

  <!-- ________________________________________________________________________
       <digitGroup>
  -->
  <xs:group name="digitGroup">
    <xs:choice>
      <xs:element  name="device"  type="deviceType"/>
      <xs:element  name="plane"   type="planeType"/>
      <xs:element  name="segment" type="segmentType"/>
      <xs:element  name="ch"      type="chType"/>
      <xs:element  name="data"	  type="dataType"/>
      <xs:element  name="for"	  type="forType"/>
    </xs:choice>
  </xs:group>
	    

  <!-- ______________________________________________________________________-->
  <!-- ______________________________________________________________________-->
  <!-- _________________________________________________________________________
       compexType definition
  -->


  <!-- _________________________________________________________________________
       <digit_dataType>
  -->
  <xs:complexType name="digit_dataType">
    <xs:group ref="deviceGroup"	minOccurs="0" maxOccurs="unbounded"/>
  </xs:complexType>

  <!-- _________________________________________________________________________
       <dataType>
  -->
  <xs:complexType name="dataType">
    <xs:attributeGroup ref="digitAttrs"/>
  </xs:complexType>

  <!-- _________________________________________________________________________
       <chType>
  -->
  <xs:complexType name="chType">
    <xs:group ref="dataGroup" minOccurs="0" maxOccurs="unbounded"/>
    <xs:attributeGroup ref="digitAttrs"/>
  </xs:complexType>

  <!-- _________________________________________________________________________
       <segmentType>
  -->
  <xs:complexType name="segmentType">
    <xs:group     ref="chGroup"	minOccurs="0" maxOccurs="unbounded"/>
    <xs:attributeGroup ref="digitAttrs"/>
  </xs:complexType>


  <!-- _________________________________________________________________________
       <planeType>
  -->
  <xs:complexType name="planeType">
    <xs:group	  ref="segmentGroup" minOccurs="0" maxOccurs="unbounded"/>
    <xs:attributeGroup ref="digitAttrs"/>
  </xs:complexType>


  <!-- _________________________________________________________________________
       <deviceType>
  -->
  <xs:complexType name="deviceType">
    <xs:group ref="planeGroup" minOccurs="0" maxOccurs="unbounded"/>
    <xs:attributeGroup ref="digitAttrs"/>
  </xs:complexType>

  <!-- _________________________________________________________________________
       <forType>
  -->
  <xs:complexType name="forType">
    <xs:group	  ref="digitGroup" minOccurs="0" maxOccurs="unbounded"/>
    <xs:attribute name="var"  type="xs:string" use="required"/>
    <xs:attribute name="from" type="xs:string" use="required"/>
    <xs:attribute name="to"   type="xs:string" use="required"/>
    <xs:attribute name="step" type="xs:int"    default="1"/>
  </xs:complexType>

</xs:schema>

=== hyptpc/k18-analyzer/e73_2024/param/DIGIT/digit_data_e73_20240505.xml
<?xml version="1.0" encoding="UTF-8" ?>

<digit_data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	    xsi:noNamespaceSchemaLocation="schema/digit.xsd">

  <device id="0xff" name="null"/>
  <!--________________________________________________________________-->
  <device id="0" name="CDH" type="Hodo"><for var="seg" from="0" to="35">
    <segment id="seg"><for var="UorD" from="0" to="1">
      <ch id="UorD">
        <data id="0" name="adc"/>
        <data id="1" name="leading"/>
        <data id="2" name="trailing"/>
	<data id="3" name="commonstop"/>
	<data id="4" name="overflow"/>
      </ch></for>
    </segment></for>
  </device>
  <!--________________________________________________________________-->
  <device id="1" name="BHT" type="Hodo"><for var="seg" from="0" to="63">
    <segment id="seg"><for var="UorD" from="0" to="1">
      <ch id="UorD">
        <data id="0" name="leading"/>
        <data id="1" name="trailing"/>
	<data id="2" name="commonstop"/>
	<data id="3" name="overflow"/>
	<data id="4" name="adc"/>
      </ch></for>
    </segment></for>
  </device>
  <!--________________________________________________________________-->
  <device id="2" name="T0" type="Hodo"><for var="seg" from="0" to="4">
    <segment id="seg"><for var="UorD" from="0" to="1">
      <ch id="UorD">
        <data id="0" name="adc"/>
        <data id="1" name="leading"/>
        <data id="2" name="trailing"/>
	<data id="3" name="commonstop"/>
	<data id="4" name="overflow"/>
      </ch></for>
    </segment></for>
  </device>
  <!--________________________________________________________________-->
  <device id="3" name="AC" type="Hodo"><for var="seg" from="0" to="4">
    <segment id="seg">
      <ch id="0">
        <data id="0" name="adc"/>
        <data id="1" name="leading"/>
        <data id="2" name="trailing"/>
	<data id="3" name="commonstop"/>
	<data id="4" name="overflow"/>
      </ch>
    </segment></for>
  </device>
  <!--________________________________________________________________-->
  <device id="4" name="T1" type="Hodo">
    <segment id="0"><for var="LorR" from="0" to="1">
      <ch id="LorR">
        <data id="0" name="adc"/>
        <data id="1" name="leading"/>
        <data id="2" name="trailing"/>
	<data id="3" name="commonstop"/>
	<data id="4" name="overflow"/>
      </ch></for>
    </segment>
  </device>
  <!--________________________________________________________________-->
  <device id="5" name="E0" type="Hodo"><for var="seg" from="0" to="2">
      <segment id="seg"><for var="UorD" from="0" to="1">
	  <ch id="UorD">
            <data id="0" name="adc"/>
            <data id="1" name="leading"/>
            <data id="2" name="trailing"/>
	    <data id="3" name="commonstop"/>
	    <data id="4" name="overflow"/>
	</ch></for>
    </segment></for>
  </device>
  <!--________________________________________________________________-->
  <device id="6" name="DEF" type="Hodo"><for var="seg" from="0" to="4">
      <segment id="seg"><for var="UorD" from="0" to="1">
	  <ch id="UorD">
            <data id="0" name="adc"/>
            <data id="1" name="leading"/>
            <data id="2" name="trailing"/>
	    <data id="3" name="commonstop"/>
	    <data id="4" name="overflow"/>
	</ch></for>
    </segment></for>
  </device>
  <!--________________________________________________________________-->
  <device id="14" name="CVC" type="Hodo"><for var="seg" from="0" to="34">
    <segment id="seg"><for var="UorD" from="0" to="1">
      <ch id="UorD">
        <data id="0" name="adc"/>
        <data id="1" name="leading"/>
        <data id="2" name="trailing"/>
	<data id="3" name="commonstop"/>
	<data id="4" name="overflow"/>
      </ch></for>
    </segment></for>
  </device>
  <!--________________________________________________________________-->
  <device id="29" name="PbG" type="Hodo"><for var="seg" from="0" to="39">
    <segment id="seg">
      <data id="0" name="adc"/>
      <data id="1" name="leading"/>
      <data id="2" name="trailing"/>
      <data id="3" name="commonstop"/>
      <data id="4" name="overflow"/>
    </segment></for>
  </device>
  <!--________________________________________________________________-->
  <device id="30" name="PbF2" type="Hodo"><for var="seg" from="0" to="39">
    <segment id="seg">
      <data id="0" name="adc"/>
      <data id="1" name="leading"/>
      <data id="2" name="trailing"/>
      <data id="3" name="commonstop"/>
      <data id="4" name="overflow"/>
    </segment></for>
  </device>
  <!--________________________________________________________________-->
  <device id="31" name="Veto" type="Hodo"><for var="seg" from="0" to="3">
    <segment id="seg"><for var="UorD" from="0" to="1">
      <ch id="UorD">
        <data id="0" name="adc"/>
        <data id="1" name="leading"/>
        <data id="2" name="trailing"/>
	<data id="3" name="commonstop"/>
	<data id="4" name="overflow"/>
      </ch></for>
    </segment></for>
  </device>
  <!--________________________________________________________________-->
  <device id="32" name="NC" type="Hodo"><for var="seg" from="0" to="5">
    <segment id="seg"><for var="UorD" from="0" to="1">
      <ch id="UorD">
        <data id="0" name="adc"/>
        <data id="1" name="leading"/>
        <data id="2" name="trailing"/>
	<data id="3" name="commonstop"/>
	<data id="4" name="overflow"/>
      </ch></for>
    </segment></for>
  </device>
  <!--________________________________________________________________-->
  <device id="33" name="BTC" type="Hodo"><for var="seg" from="0" to="1">
    <segment id="seg"><for var="UorD" from="0" to="1">
      <ch id="UorD">
        <data id="0" name="adc"/>
        <data id="1" name="leading"/>
        <data id="2" name="trailing"/>
	<data id="3" name="commonstop"/>
	<data id="4" name="overflow"/>
      </ch></for>
    </segment></for>
  </device>
  <!--________________________________________________________________-->
  <device id="34" name="Leak" type="Hodo"><for var="seg" from="0" to="5">
    <segment id="seg"><ch id="0">
      <data id="0" name="adc"/>
      <data id="1" name="leading"/>
      <data id="2" name="trailing"/>
      <data id="3" name="commonstop"/>
      <data id="4" name="overflow"/>
    </ch></segment></for>
  </device>
  <!--________________________________________________________________-->
  <device id="98" name="RC" type="Hodo"><for var="seg" from="0" to="7">
      <segment id="seg"><for var="UorD" from="0" to="1">
	  <ch id="UorD">
            <data id="0" name="adc"/>
            <data id="1" name="leading"/>
            <data id="2" name="trailing"/>
	    <data id="3" name="commonstop"/>
	    <data id="4" name="overflow"/>
	</ch></for>
    </segment></for>
  </device>
  <!--________________________________________________________________-->
  <device id="81" name="VME-RM">
    <plane id="0" name="vme01">
      <ch id="0" name="tag">
	<data id="0" name="event"/>
	<data id="1" name="spill"/>
	<data id="2" name="serial"/>
	<data id="3" name="time"/>
      </ch>
      <ch id="1" name="lock_bit">
	<data id="0" name="event"/>
	<data id="1" name="spill"/>
	<data id="2" name="serial"/>
	<data id="3" name="time"/>
      </ch>
    </plane>
    <plane id="1" name="vme02">
      <ch id="0" name="tag">
	<data id="0" name="event"/>
	<data id="1" name="spill"/>
	<data id="2" name="serial"/>
	<data id="3" name="time"/>
      </ch>
      <ch id="1" name="lock_bit">
	<data id="0" name="event"/>
	<data id="1" name="spill"/>
	<data id="2" name="serial"/>
	<data id="3" name="time"/>
      </ch>
    </plane>
    <plane id="2" name="vme03">
      <ch id="0" name="tag">
	<data id="0" name="event"/>
	<data id="1" name="spill"/>
	<data id="2" name="serial"/>
	<data id="3" name="time"/>
      </ch>
      <ch id="1" name="lock_bit">
	<data id="0" name="event"/>
	<data id="1" name="spill"/>
	<data id="2" name="serial"/>
	<data id="3" name="time"/>
      </ch>
    </plane>
  </device>
  <!--________________________________________________________________-->
  <device id="82" name="HUL-RM"><for var="seg" from="0" to="15">
    <segment id="seg"><for var="UorD" from="0" to="1">
      <ch id="UorD">
        <data id="0" name="leading"/>
        <data id="1" name="trailing"/>
        <data id="2" name="hitnum"/>
	<data id="3" name="event"/>
	<data id="4" name="spill"/>
	<data id="5" name="sinc"/>
	<data id="6" name="lock"/>
      </ch></for>
    </segment></for>
  </device>
  <!--________________________________________________________________-->
  <device id="91" name="Scaler">
    <plane id="0">
      <for var="ch" from="0" to="63">
	<ch id="ch">
	  <data id="0" name="scaler"/>
	  <data id="1" name="event"/>
	  <data id="2" name="spill"/>
	  <data id="3" name="sinc"/>
	  <data id="4" name="lock"/>
	</ch>
      </for>
    </plane>
    <plane id="1">
      <for var="ch" from="0" to="63">
	<ch id="ch">
	  <data id="0" name="scaler"/>
	  <data id="1" name="event"/>
	  <data id="2" name="spill"/>
	  <data id="3" name="sinc"/>
	  <data id="4" name="lock"/>
	</ch>
      </for>
    </plane>
  </device>
  <!--________________________________________________________________-->
  <device id="99" name="TriggerFlag" type="Hodo"><for var="seg" from="0" to="127">
    <segment id="seg">
      <data id="0" name="adc"/>
      <data id="1" name="leading"/>
      <data id="2" name="trailing"/>
      <data id="3" name="overflow"/>
    </segment></for>
  </device>
  <!--________________________________________________________________-->
  <device id="53" name="VFT" type="Fiber">
    <for var="plane" from="0" to="13"><for var="seg" from="0" to="63">
      <plane id="plane"><segment id="seg">
	  <data id="0" name="leading"/>
	  <data id="1" name="trailing"/>
